name: python-workshop
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.10
  - jupyterlab=4.0.11
  - jupyter
  - plotnine=0.13.6
  - pandas=2.2.2
  - numpy
  # The quatro package on conda-forge currently appears broken
  # Once this is fixed we should install quarto this way
  - quarto
