on:
  workflow_dispatch:
  push:
    branches: [master, quarto]

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      # - name: Install Conda environment from conda-environment.frozen.yml
      #   uses: mamba-org/provision-with-micromamba@main
      #   with:
      #     environment-file: conda-environment.frozen.yml
      #     cache-downloads: true
      #     cache-env: true

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Python and Dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install -r requirements.txt

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          # path: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}