on:
  workflow_dispatch:
  push:
    branches: [master]

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Conda environment from conda-environment.frozen.yml
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: conda-environment.frozen.yml
          cache-downloads: true
          cache-env: true

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}